/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Code: typeof import('./../components/code.vue')['default']
    CommonFileUpload: typeof import('./../components/common/fileUpload.vue')['default']
    CommonPagination: typeof import('./../components/common/pagination.vue')['default']
    ComputeCode: typeof import('./../components/computeCode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
